#include <stdexcept>

int main(int argc, char * argv[])
{
    try
    {
        
    } catch (std::exception const & e)
    {
        return 1;
    }

    return 0;
}